TrabajoFinal/Models/Instructor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TrabajoFinal.Models
{
    public class Instructor
    {
        [Key]
        public int Id { get; set; }
        [Required][StringLength(100)]
        public string Name { get; set; }
        [Required][DataType(DataType.Date)]
        public DateTime HireDate { get; set; }
    }
}

TrabajoFinal/Controllers/InstructorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrabajoFinal.Dal;
using TrabajoFinal.Models;
using TrabajoFinal.Services;

namespace TrabajoFinal.Controllers
{
    public class InstructorsController : Controller
    {        
        private SchoolRepository repo = new SchoolRepository();

        // GET: Instructors
        public ActionResult Index()
        {
            List<Instructor> instructors = (List<Instructor>)repo.GetList("Instructor", "", null);

            return View(instructors);
        }
        public ActionResult Search(FormCollection form)
        {
            string name = form["Name"];

            List<Instructor> instructors = (List<Instructor>)repo.GetList("Instructor", name, null);

            return View("Index", instructors);
        }

        // GET: Instructors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Instructors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,HireDate")] Instructor instructor)
        {
            if (ModelState.IsValid)
            {
                repo.Create(instructor, "Instructor");
                return RedirectToAction("Index");
            }

            return View(instructor);
        }

        // GET: Instructors/Edit/5
        public ActionResult Edit(int id)
        {
            Instructor instructor = (Instructor)repo.GetOne(id, "Instructor");

            return View(instructor);
        }

        // POST: Instructors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,HireDate")] Instructor instructor)
        {
            if (ModelState.IsValid)
            {
                repo.Edit(instructor, "Instructor");
                return RedirectToAction("Index");
            }
            return View(instructor);
        }
        public ActionResult Delete(int id)
        {   
            repo.Delete(id, "Instructor");

            return RedirectToAction("Index");
        }
    }
}

TrabajoFinal/Views/Instructors/Create.cshtml
@model TrabajoFinal.Models.Instructor

@{
    ViewBag.Title = "New Instructor";
}

<h2>New Instructor</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label text-center col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.HireDate, htmlAttributes: new { @class = "control-label text-center col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HireDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-5">

                @Html.ActionLink("Clear", "Create", null, new { @class = "btn btn-outline-danger float-right" })
                <input type="submit" value="Create" class="btn btn-outline-success float-right mr-4" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrabajoFinal/Views/Instructors/Edit.cshtml
@model TrabajoFinal.Models.Instructor

@{
    ViewBag.Title = "Instructor Edition";
}

<h2>Instructor Edition</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            <label for="Id" class="control-label text-center col-2">Instructor ID</label>
            <div class="col-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label text-center col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.HireDate, htmlAttributes: new { @class = "control-label text-center col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HireDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-5">

                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-outline-danger float-right" })
                <input type="submit" value="Save" class="btn btn-outline-success float-right mr-4" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrabajoFinal/Views/Instructors/Index.cshtml
@model List<TrabajoFinal.Models.Instructor>

@{
    ViewBag.Title = "Instructors List";
}

<h1 class="text-center mb-5">Instructors List</h1>

@using (Html.BeginForm("Search", "Instructors"))
{
    <div class="row mb-5">

        <label for="Name" class="control-label col-1">Name:</label>
        <input type="text" id="Name" name="Name" class="form-control col-6" placeholder="Ej: Antonio Juarez" />

        <div class="form-group col-5 mb-5">
            <input class="btn btn-outline-dark" type="submit" value="Buscar" />
        </div>
    </div>
}

<div class="row mt-5">
    <table class="table table-sm table-bordered table-striped table-hover col-10">
        <thead>
            <tr class="table-secondary">
                <th>Instructor Id</th>
                <th>Instructor's Full Name</th>
                <th>Hire Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        <td>@Html.DisplayFor(modelItem => item.HireDate)</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-link" }) |
                            @Html.Partial("_Delete", item)
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="4" class="text-center">No Instructors available yet</td>
                </tr>
            }
        </tbody>
    </table>

    <div class="col-2">
        @Html.ActionLink("+", "Create", null, new { @class = "btn btn-outline-secondary text-center col-sm-3", style = "border-radius: 50%;" })
    </div>
</div>

TrabajoFinal/Views/Instructors/_Delete.cshtml
@model TrabajoFinal.Models.Instructor

<button type="button" class="btn btn-link" data-toggle="modal" data-target="#modal-@Model.Id">Remove</button>

<!-- Modal -->
<div class="modal fade" id="modal-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="modalLabel-@Model.Id" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel-@Model.Id">Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h4>You are deleting the instructor @Model.Name, are you sure you want to continue?</h4>
                <p class="text-secondary text-sm-left">If any course with this instructor have some students, you won't can delete it.</p>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Yes", "Delete", new { id = Model.Id }, new { @class = "btn btn-outline-danger" })
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>