TrabajoFinal/Controllers/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrabajoFinal.Models;
using TrabajoFinal.Services;

namespace TrabajoFinal.Controllers
{
    public class EnrollmentsController : Controller
    {
        private SchoolRepository repo = new SchoolRepository();

        // GET: Enrollments
        public ActionResult Index()
        {
            List<Course> courses = (List<Course>)repo.GetList("Enrollment", "", null);

            ViewBag.Departments = (List<Department>)repo.GetList("Department", "", null);

            bool? enrolled = (bool?)Session["Enrolled"];
            ViewBag.Enrolled = enrolled;

            Session["Enrolled"] = null;

            return View(courses);
        }
        public ActionResult Search(FormCollection form)
        {
            string title = form["Title"];
            int id = Convert.ToInt32(form["Department"]);

            List<Course> courses = (List<Course>)repo.GetList("Enrollment", title, id);

            ViewBag.Departments = (List<Department>)repo.GetList("Department", "", null);

            return View("Index", courses);
        }

        [HttpPost]
        public ActionResult Enroll(FormCollection form)
        {
            var student = new Student();
            student.FullName = form["FullName"];
            student.Email = form["Email"];
            int courseId = Convert.ToInt32(form["Id"]);

            Session["Enrolled"] = repo.Enroll(courseId, student);

            return RedirectToAction("Index");
        }
    }
}

TrabajoFinal/Views/Enrollments/Index.cshtml
@model List<TrabajoFinal.Models.Course>

@{
    ViewBag.Title = "Course Enrollment";
}

<h1 class="text-center mb-5">Course Enrollment</h1>
@if (ViewBag.Enrolled != null && ViewBag.Enrolled)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <p>You have been enrolled!</p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
else if (ViewBag.Enrolled != null && !ViewBag.Enrolled)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <p>You cannot enroll this course because you are already in it</p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@using (Html.BeginForm("Search", "Enrollments"))
{
    <div class="row mb-2">
        <div class="form-group col-3">
            <label for="Department" class="control-label">Department:</label>
            <select id="Department" name="Department" class="form-control">
                <option value="0">All</option>
                @foreach (var department in (List<TrabajoFinal.Models.Department>)ViewBag.Departments)
                {
                    <option value="@department.Id">@department.Title</option>
                }
            </select>
        </div>
        <div class="form-group col-9 row-cols-2">
            <label for="Title" class="control-label">Title:</label>
            <div>
                <input type="text" id="Title" name="Title" class="form-control col-12" placeholder="Ej: Spanish" />
            </div>
        </div>
    </div>
    <div class="form-group mb-5">
        <input class="btn btn-outline-dark" type="submit" value="Buscar" />
    </div>
}


<table class="table table-sm table-bordered table-striped table-hover mt-5">
    <thead>
        <tr class="table-secondary">
            <th>Course ID</th>
            <th>Title</th>
            <th>Aviable Seats</th>
            <th>Department</th>
            <th>Instructor</th>
            <th>Enroll</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            foreach (var item in Model)
            {
                int aviableSeats = item.Capacity - item.Students.Count();

                <tr>
                    <td>@item.Id</td>
                    <td>@item.Title</td>
                    <td>@aviableSeats/@item.Capacity</td>
                    <td>@Html.DisplayFor(modelItem => item.Department.Title)</td>
                    <td>@Html.DisplayFor(modelItem => item.Instructor.Name)</td>
                    @if(aviableSeats > 0)
                    {
                    <td>
                        <button type="button" class="btn btn-link" data-toggle="modal" data-target="#modal-@item.Id">Enroll</button>
                        @Html.Partial("_Enroll", item)
                    </td>
                    }
                    else
                    {
                        <td>
                            <button type="button" class="btn btn-link text-secondary" disable>Enroll</button>
                        </td>
                    }
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6" class="text-center">No Courses available yet</td>
            </tr>
        }
    </tbody>
</table>

TrabajoFinal/Views/Enrollments/_Enroll.cshtml
@model TrabajoFinal.Models.Course
@{var student = new TrabajoFinal.Models.Student(); }
<!-- Button trigger modal -->
    

<!-- Modal -->
<div class="modal fade" id="modal-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="modalLabel-@Model.Id" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel-@Model.Id">Enroll Student</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Enroll", "Enrollments"))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-horizontal">
                        <h4 class="text-center">Student Enrollment</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group row">
                            <label for="FullName" class="control-label text-center col-4">Full Name</label>
                            <div class="col-8">
                                <input type="text" name="FullName" id="FullName" class="form-control" required/>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="Email" class="control-label text-center col-4">Email</label>
                            <div class="col-8">
                                <input type="email" name="Email" id="Email" class="form-control" required />
                            </div>
                        </div>

                        <div class="form-group d-flex justify-content-center align-content-center">
                            <input type="submit" value="Enroll" class="btn btn-outline-success mr-3" />
                            <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}