TrabajoFinal/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TrabajoFinal.Models
{
    public class Department
    {
        [Key]
        public int Id { get; set; }
        [Required][StringLength(50)]
        public string Title { get; set; }
        [Required][StringLength(200)][DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public List<Course> Courses { get; set; }
    }
}

TrabajoFinal/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrabajoFinal.Dal;
using TrabajoFinal.Models;
using TrabajoFinal.Services;

namespace TrabajoFinal.Controllers
{
    public class DepartmentsController : Controller
    {
        private SchoolRepository repo = new SchoolRepository();


        public ActionResult Index()
        {
            List<Department> departments = (List<Department>)repo.GetList("Department", "", null);

            return View(departments);
        }
        public ActionResult Search(FormCollection form)
        {
            string title = form["Title"];

            List<Department> departments = (List<Department>)repo.GetList("Department", title, null);

            return View("Index", departments);
        }

        // GET: Departments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Description")] Department department)
        {
            if (ModelState.IsValid)
            {
                repo.Create(department, "Department");
                return RedirectToAction("Index");
            }

            return View(department);
        }

        // GET: Departments/Edit/5
        public ActionResult Edit(int id)
        {
            Department department = (Department)repo.GetOne(id, "Department");

            return View(department);
        }

        // POST: Departments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description")] Department department)
        {
            if (ModelState.IsValid)
            {
                repo.Edit(department, "Department");
                return RedirectToAction("Index");
            }
            return View(department);
        }
        public ActionResult Delete(int id)
        {

            repo.Delete(id, "Department");

            return RedirectToAction("Index");
        }
    }
}

TrabajoFinal/Views/Departments/Create.cshtml
@model TrabajoFinal.Models.Department

@{
    ViewBag.Title = "New Deparment";
}

<h2>New Deparment</h2>
<hr />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            <label for="Title" class="control-label text-center col-2">Department Title</label>
            <div class="col-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label text-center col-2" })
            <div class="col-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-5">

                @Html.ActionLink("Clear", "Create", null, new { @class = "btn btn-outline-danger float-right" })
                <input type="submit" value="Create" class="btn btn-outline-success float-right mr-4" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrabajoFinal/Views/Departments/Edit.cshtml
@model TrabajoFinal.Models.Department

@{
    ViewBag.Title = "Depatment Edition";
}

<h2>Depatment Edition</h2>
<hr />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            <label for="Id" class="control-label text-center col-2">Department ID</label>
            <div class="col-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group row">
            <label for="Title" class="control-label text-center col-2">Department Title</label>
            <div class="col-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label text-center col-2" })
            <div class="col-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-5">

                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-outline-danger float-right" })
                <input type="submit" value="Save" class="btn btn-outline-success float-right mr-4" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrabajoFinal/Views/Departments/Index.cshtml
@model List<TrabajoFinal.Models.Department>

@{
    ViewBag.Title = "Departments List";
}

    <h1 class="text-center mb-5">Departments List</h1>

@using (Html.BeginForm("Search", "Departments"))
{
    <div class="row mb-5">
        
            <label for="Title" class="control-label col-1">Title:</label>
            <input type="text" id="Title" name="Title" class="form-control col-6" placeholder="Ej: Math" />
        
        <div class="form-group col-5 mb-5">
            <input class="btn btn-outline-dark" type="submit" value="Buscar" />
        </div>
    </div>
}

<div class="row mt-5">
    <table class="table table-sm table-bordered table-striped table-hover col-10">
        <thead>
            <tr class="table-secondary">
                <th>Department ID</th>
                <th>Department Title</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Title</td>
                        <td>@item.Description</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-link" }) |
                            @Html.Partial("_Delete", item)
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="4" class="text-center">No departments available yet</td>
                </tr>
            }
        </tbody>
    </table>

    <div class="col-2">
        @Html.ActionLink("+", "Create", null, new { @class = "btn btn-outline-secondary text-center col-sm-3", style = "border-radius: 50%;" })
    </div>
</div>

TrabajoFinal/Views/Departments/_Delete.cshtml
@model TrabajoFinal.Models.Department

<!-- Button trigger modal -->
<button type="button" class="btn btn-link" data-toggle="modal" data-target="#modal-@Model.Id">Remove</button>

<!-- Modal -->
<div class="modal fade" id="modal-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="modalLabel-@Model.Id" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel-@Model.Id">Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h4>You are deleting department @Model.Title, all corresponding courses will also be deleted. 
                    <br />Are you sure you want to continue?</h4>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Yes", "Delete", new { id = Model.Id }, new { @class = "btn btn-outline-danger" })
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>